const SEARCH = 'SEARCH';
const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
const SEARCH_ORGS = 'SEARCH_ORGS';
const SEARCH_ORGS_SUCCESS = 'SEARCH_ORGS_SUCCESS';
const USER_NOT_FOUND = 'USER_NOT_FOUND';
const ERROR_RESPONSE = 'ERROR_RESPONSE';

export {
  SEARCH,
  SEARCH_REPOSITORIES_SUCCESS,
  SEARCH_USER_SUCCESS,
  SEARCH_REPOSITORIES,
  SEARCH_ORGS,
  SEARCH_ORGS_SUCCESS,
  USER_NOT_FOUND,
  ERROR_RESPONSE,
};
